dependencies:
  - python=3.7
  - pip
  - pip:
    - jupyter
    - jupyterlab>=3.0.0
    - jupyter-server-proxy
    - jupyter_bokeh
    - hover==0.4.0
    - spacy
    - umap-learn
    - faker
    - wrappy
