dependencies:
  - python=3.8
  - pip
  - pip:
    - jupyter-server-proxy
    - jupyter_bokeh
    - git+https://github.com/phurwicz/hover.git
    - faker
    - spacy
    - snorkel>=0.9.8
    - wrappy>=0.2.6
    - efficientnet_pytorch
    - torchvision
    - torchaudio
    - librosa
