dependencies:
  - python=3.8
  - pip
  - pip:
    - jupyter-server-proxy
    - jupyter_bokeh
    - hover==0.8.0
    - faker
    - spacy
    - snorkel>=0.9.8
    - wrappy>=0.2.6
    - efficientnet_pytorch
    - torchvision
    - torchaudio
    - librosa
